---
title: "Additional Information"
output: html_document
---

\#**What is TF-IDF?**

TF-IDF stands for term frequency-inverse document frequency. This model can be applied to a few different purposes, but I use it specifically for text summarization and keyword extraction to find and quantify the importance of specific words in Spice Girls songs.

Term frequency: There are multiple ways to define frequency, but here, it means the frequency of a particular word in the songs; how often a word is said in a song.

Inverse document frequency: I use this to find how common or uncommon a word is in the lyrics. This is particularly important to filter out filler words like "of" and "as."

Using both TF and IDF, I tried to find which words hold the most relevance in their songs. The higher the TF-IDF score, the more relevance the word holds in the song, while the less relevant it is, the closer the score is to zero.

This model isn't perfect, though. There may be some words, like "love," that are extremely common in their songs. However, their tf-idf score may be low because it is not especially unique, though it is still extremely important.

https://www.capitalone.com/tech/machine-learning/understanding-tf-idf/

\#**What is LDA Analysis?**

LDA analysis is a "probabilistic generative model" used here to analyze a collection of text–Spice Girls lyrics. You could also use this for articles, books, and other text. LDA approaches documents as a collection of themes or "Topics," which it them hopes to uncover by analyzing the words of the document.

https://medium.com/@pinakdatta/understanding-lda-unveiling-hidden-topics-in-text-data-9bbbd25ae162

https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation#:\~:text=In%20natural%20language%20processing%2C%20latent,of%20a%20Bayesian%20topic%20model.
