# Proposal {.unnumbered}

Project Proposal Mayumi Morgan, Cody Da, Jack Hou, and Enrico Verità Data set: Spice up your Life

We will analyze the data set "Spice up your Life" which contains information regarding the famous music group the Spice Girls. This data set contains information on album release date, energy, liveliness, danceability, and general statistics on various Spice Girl tracks. We chose this set because we are interested in music and this seems fun and interesting topic. We want to analyze lyrics and maybe analyze which band member sings the most, or we could see which song is the best to dance to.

**Overarching research question:**

-   What kind of music did the spice girls make?

    -   Did their music style change over time? If so, how

-   What kind of themes did the Spice Girls sing about?

-   Who was the most popular member

    -   Who sang the most lines?

**Why is it important:**

-   The Spice Girls were a large part of the cultural zeitgeist of the 90s and early 2000s, influencing music, fashion, as well as other artists. Despite their relatively short time as a group, they remain popular is, as shown by their Olympic performance in 2012 at the London Olympic over a decade after their official disbandment. In 2019 the group reunited and embarked on a European tour. The "Spice World" tour became the highest grossing all-female tour from 2000-2020. This begs the question: what makes their music so successfull?

Where the data comes from:

The data in this repo comes from [Spotify](https://www.spotify.com/) and [Genius](https://www.genius.com/). Thank you to the authors of the `spotifyr` and `geniusr` packages for making it easy to access data from these platforms!

There are 3 data sets about or related to the Spice Girls:

-   `studio_album_tracks`: Audio features of each song from the three studio albums by the Spice Girls. From Spotify.

-   `related artists`: Artists deemed to be similar to the Spice Girls, with info about each artist including their musical genres and follower numbers. Includes a row with details for the Spice Girls, for comparison purposes. From Spotify.

-   `lyrics`: Lyrics of each song from the three studio albums by the Spice Girls. From Genius.

Credit: [Jacquie Tran](https://www.twitter.com/jacquietran)

\*taken from Tidytuesday
